import type { DayInfo, TrekMeta, Waypoint } from "./types";

export const TREK_META: TrekMeta = {
  expedition: "618-J",
  itinerary: "12-1 Challenging",
  route: "South Country Loop",
  totalMiles: 53.3,
  totalGainFt: 30700,
  totalLossFt: 27540,
  elevMinFt: 6729,
  elevMaxFt: 9343,
  startDate: "2026-06-18",
  endDate: "2026-06-29",
  crew: "Crew 618-J",
  numHikingDays: 11,
};

export const DAYS: Record<number, DayInfo> = {
  2: {
    day: 2,
    date: "June 19",
    from: "Base Camp",
    to: "Olympia",
    miles: 2.6,
    gainFt: 520,
    lossFt: 300,
    startElevFt: 6729,
    endElevFt: 6731,
    campType: "trail",
    hasShowers: false,
    color: "#ef4444",
    mapImages: ["day_02-1.png"],
    programs: [
      "Ranger shakedown at Rayado Trailhead",
      "Ranger backcountry training (LNT, bear bags, water, stoves)",
      "Kit Carson Museum passthrough at Rayado",
    ],
    callout: null,
    warning: null,
    special: null,
    highlight: null,
    tips: [
      "Trekking poles accessible for Rayado Creek crossings — feet will likely get wet",
      "Hang bear bags tonight — build the habit from day 1",
      "First night at altitude; encourage extra hydration",
    ],
    passthrough: ["Rayado"],
  },

  3: {
    day: 3,
    date: "June 20",
    from: "Olympia",
    to: "Abreu",
    miles: 3.3,
    gainFt: 600,
    lossFt: 110,
    startElevFt: 6731,
    endElevFt: 7350,
    campType: "staffed",
    hasShowers: true,
    color: "#f97316",
    mapImages: ["day_03-1.png", "day_03-2.png"],
    programs: [
      "Mexican Homestead (living history, 1912 NM — goat keeping, adobe, fiber arts)",
      "Cantina — cold root beer, peanuts, maps, games",
      "Mexican dinner served by Abreu staff",
      "Historic lodge and cabin tours",
    ],
    callout: null,
    warning: null,
    special: null,
    highlight: null,
    tips: [
      "Bring small cash for the cantina (cash-only; debit uncertain)",
      "Arrive with time before dinner to do homestead program and cantina",
      "Showers available — last chance until Day 6 at Beaubien",
    ],
    passthrough: [],
  },

  4: {
    day: 4,
    date: "June 21",
    from: "Abreu",
    to: "Fish Camp",
    miles: 7.9,
    gainFt: 6970,
    lossFt: 5480,
    startElevFt: 7350,
    endElevFt: 8500,
    campType: "trail",
    hasShowers: false,
    color: "#eab308",
    mapImages: ["day_04-1.png", "day_04-2.png", "day_04-3.png"],
    programs: [
      "Trail camp — no staff programs (crew listed as No Services in 2026 itinerary)",
      "Self-guided fishing in Rayado Creek (NM license required)",
    ],
    callout: "Hardest day — 6,970’ cumulative gain",
    warning: null,
    special: null,
    highlight: null,
    tips: [
      "Start early — 7.9 mi with massive gain/loss",
      "NM fishing license required: scouts 12+ ($2 Philmont youth); adults must purchase before the trail",
      "Creek-side camp — mosquitoes at dusk; bring repellent",
    ],
    passthrough: [],
  },

  5: {
    day: 5,
    date: "June 22",
    from: "Fish Camp",
    to: "Buck Creek",
    miles: 7.5,
    gainFt: 3840,
    lossFt: 3380,
    startElevFt: 8500,
    endElevFt: 9131,
    campType: "trail",
    hasShowers: false,
    color: "#22c55e",
    mapImages: ["day_05-1.png", "day_05-2.png"],
    programs: [
      "3D Archery in Jicarilla Apache style at Apache Springs",
      "Jicarilla Apache Life program — tipi tours, flint knapping, sweat lodge",
      "Commissary at Apache Springs — food/white gas resupply",
    ],
    callout: null,
    warning: null,
    special: null,
    highlight: null,
    tips: [
      "Apache Springs is the midpoint — the second half (to Buck Creek) is the harder half",
      "Top off water and resupply food at the Apache Springs commissary",
      "Flint knapping takes focused time; don’t rush programs if you want to finish it",
    ],
    passthrough: ["Apache Springs"],
  },

  6: {
    day: 6,
    date: "June 23",
    from: "Buck Creek",
    to: "Beaubien",
    miles: 3.3,
    gainFt: 1740,
    lossFt: 1570,
    startElevFt: 9131,
    endElevFt: 9330,
    campType: "staffed",
    hasShowers: true,
    color: "#14b8a6",
    mapImages: ["day_06-1.png"],
    programs: [
      "Horse rides (reservation required — book during Day 1 Base Camp check-in)",
      "Western lore — roping and leather branding (boots, belts)",
      "Chuck wagon dinner served by staff",
      "Evening western campfire",
    ],
    callout: "Horse rides and chuckwagon dinner at Beaubien",
    warning: null,
    special: null,
    highlight: null,
    tips: [
      "Horse ride slots fill fast — Lead Advisor must book during Day 1 check-in",
      "Bring a leather item (hiking boot, belt) to brand — a lasting souvenir",
      "Showers available; slow walk around the meadow at dusk is one of Philmont’s best views",
    ],
    passthrough: [],
  },

  7: {
    day: 7,
    date: "June 24",
    from: "Beaubien",
    to: "Beaubien",
    miles: 0,
    gainFt: 0,
    lossFt: 0,
    startElevFt: 9330,
    endElevFt: 9330,
    campType: "layover",
    hasShowers: true,
    color: "#6366f1",
    mapImages: ["day_07-1.png"],
    programs: [
      "Conservation project — 7:30am start (forest fuel reduction; Arrowhead Award credit)",
      "All Beaubien programs remain open (horses, branding, roping)",
      "Optional day hike to Black Mountain to preview Day 8’s approach",
    ],
    callout: null,
    warning: null,
    special: "Layover — Conservation Project",
    highlight: null,
    tips: [
      "Last showers until Miners Park (Day 8) — use them",
      "Blister management today prevents injury on Day 8’s hardest climb",
      "Brief the crew on Day 8 tonight so they go to bed mentally prepared",
    ],
    passthrough: [],
  },

  8: {
    day: 8,
    date: "June 25",
    from: "Beaubien",
    to: "Miners Park",
    miles: 8.6,
    gainFt: 4320,
    lossFt: 5640,
    startElevFt: 9330,
    endElevFt: 8002,
    campType: "staffed",
    hasShowers: true,
    color: "#3b82f6",
    mapImages: ["day_08-1.png", "day_08-2.png"],
    programs: [
      "Blackpowder Settlement — blacksmithing and gold panning at Black Mountain",
      "Rock climbing at Betty’s Bra formation (Miners Park)",
      "Commissary at Miners Park — food resupply",
    ],
    callout: "Rock climbing + Black Mountain south-face ascent",
    warning: null,
    special: null,
    highlight: null,
    tips: [
      "Start early — this is the longest and most demanding day",
      "Carry 2L minimum from Beaubien for the exposed Black Mountain climb",
      "Set a hard turnaround time at Black Mountain to reach Miners Park before dark",
    ],
    passthrough: ["Black Mountain"],
  },

  9: {
    day: 9,
    date: "June 26",
    from: "Miners Park",
    to: "Bear Caves",
    miles: 3.1,
    gainFt: 1780,
    lossFt: 1380,
    startElevFt: 8002,
    endElevFt: 8423,
    campType: "trail",
    hasShowers: false,
    color: "#8b5cf6",
    mapImages: ["day_09-1.png"],
    programs: [
      "Continental Tie & Lumber Co. at Crater Lake — spar pole climbing, crosscut saw, broadaxe",
    ],
    callout: null,
    warning: null,
    special: null,
    highlight: null,
    tips: [
      "Long pants strongly recommended (required) for spar pole climbing",
      "Bear activity common in this area — hang bags with extra care",
      "Tooth of Time visible from Crater Lake — point it out to the crew",
    ],
    passthrough: ["Crater Lake"],
  },

  10: {
    day: 10,
    date: "June 27",
    from: "Bear Caves",
    to: "Urraca",
    miles: 4.6,
    gainFt: 1780,
    lossFt: 2210,
    startElevFt: 8423,
    endElevFt: 7968,
    campType: "staffed",
    hasShowers: false,
    color: "#ec4899",
    mapImages: ["day_10-1.png"],
    programs: [
      "Challenge events (COPE-style ground-level initiatives and team problem-solving)",
      "Evening campfire with Urraca Mesa legend atmosphere",
    ],
    callout: null,
    warning: null,
    special: null,
    highlight: null,
    tips: [
      "Urraca Mesa trail involves sustained climbing — set a steady pace on accumulated miles",
      "Cattle sometimes wander through camp and trail; give them space, don’t chase",
      "Nights cold at 7,968 ft — sleeping bag liner or warm layers accessible",
    ],
    passthrough: [],
  },

  11: {
    day: 11,
    date: "June 28",
    from: "Urraca",
    to: "Stockade Ridge",
    miles: 4.7,
    gainFt: 1310,
    lossFt: 1750,
    startElevFt: 7968,
    endElevFt: 7400,
    campType: "dry",
    hasShowers: false,
    color: "#f59e0b",
    mapImages: ["day_11-1.png", "day_11-2.png"],
    programs: [
      "High COPE at RMSC (harnesses provided; high ropes, traverses, climbing tower)",
    ],
    callout: null,
    warning: "Dry camp — carry 2–3 L/person from last confirmed water source",
    special: null,
    highlight: null,
    tips: [
      "Fill water at last confirmed source before Stockade Ridge — treat any on-site source",
      "Don’t let COPE run so late that the final push to dry camp becomes a race against dark",
      "Early bed — Day 12 starts by 7am for lightning-safe Tooth of Time summit",
    ],
    passthrough: ["RMSC"],
  },

  12: {
    day: 12,
    date: "June 29",
    from: "Stockade Ridge",
    to: "Base Camp",
    miles: 7.7,
    gainFt: 2860,
    lossFt: 3720,
    startElevFt: 7400,
    endElevFt: 6729,
    campType: "staffed",
    hasShowers: false,
    color: "#78716c",
    mapImages: ["day_12-1.png", "day_12-2.png"],
    programs: [
      "Tooth of Time Class 3 scramble — 9,003 ft summit, 360° views, summit patch",
      "Awards Campfire at Base Camp — patches and program awards",
    ],
    callout: null,
    warning: null,
    special: null,
    highlight: "Tooth of Time summit (Class 3 scramble)",
    tips: [
      "Leave Stockade Ridge by 7am — summit before noon to avoid afternoon lightning",
      "Drop packs at base of the Class 3 section; summit with water and day pack only",
      "Gloves recommended for rough granite in the final scramble",
    ],
    passthrough: [],
  },
};

export const DAY_LIST = Object.values(DAYS).sort((a, b) => a.day - b.day);

export const WAYPOINTS: Waypoint[] = [
  { name: "Rayado Trailhead", lat: 36.36523,   lon: -104.930362, day: 2,  elevFt: 6513, type: "trailhead_start" },
  { name: "Olympia",          lat: 36.371734,  lon: -104.968928, day: 2,  elevFt: 6731, type: "camp", campType: "trail" },
  { name: "Abreu",            lat: 36.379133,  lon: -105.015701, day: 3,  elevFt: 7350, type: "camp", campType: "staffed" },
  { name: "Fish Camp",        lat: 36.38782,   lon: -105.10272,  day: 4,  elevFt: 8500, type: "camp", campType: "trail" },
  { name: "Apache Springs",   lat: 36.387479,  lon: -105.144133, day: 5,  elevFt: 9400, type: "passthrough" },
  { name: "Buck Creek",       lat: 36.411196,  lon: -105.130419, day: 5,  elevFt: 9131, type: "camp", campType: "trail" },
  { name: "Beaubien",         lat: 36.423576,  lon: -105.103246, day: 6,  elevFt: 9330, type: "camp", campType: "staffed" },
  { name: "Black Mountain",   lat: 36.442549,  lon: -105.093307, day: 8,  elevFt: 9200, type: "passthrough" },
  { name: "Miners Park",      lat: 36.423674,  lon: -105.041596, day: 8,  elevFt: 8002, type: "camp", campType: "staffed" },
  { name: "Crater Lake",      lat: 36.405565,  lon: -105.048942, day: 9,  elevFt: 8100, type: "passthrough" },
  { name: "Bear Caves",       lat: 36.404802,  lon: -105.033858, day: 9,  elevFt: 8423, type: "camp", campType: "trail" },
  { name: "Urraca",           lat: 36.408988,  lon: -104.990507, day: 10, elevFt: 7968, type: "camp", campType: "staffed" },
  { name: "RMSC",             lat: 36.434049,  lon: -104.990120, day: 11, elevFt: 7500, type: "passthrough" },
  { name: "Stockade Ridge",   lat: 36.437662,  lon: -105.007633, day: 11, elevFt: 7400, type: "camp", campType: "dry" },
  { name: "Tooth of Time",    lat: 36.45,      lon: -104.975,    day: 12, elevFt: 9003, type: "passthrough" },
  { name: "Base Camp",        lat: 36.453513,  lon: -104.96248,  day: 12, elevFt: 6729, type: "trailhead_end" },
];

export function getPrevDay(day: number): number | null {
  const days = DAY_LIST.map((d) => d.day);
  const idx = days.indexOf(day);
  return idx > 0 ? days[idx - 1] : null;
}

export function getNextDay(day: number): number | null {
  const days = DAY_LIST.map((d) => d.day);
  const idx = days.indexOf(day);
  return idx >= 0 && idx < days.length - 1 ? days[idx + 1] : null;
}
